github-api-key: change
wolfram-api-key: change-me
jenkins-server: http://ci.drtshock.net/
jenkins-admins: [drtshock, blha303]
bot-source-url: https://github.com/drtshock/willie
donate-url: http://tinyurl.com/drtdonate
bot-admins: [drtshock]
bot-nick: Willie
account-pass: ''
server-pass: change
server: drtshock.com
port: 5555
channels: ['#drtshock']
command-prefix: '!'
github-username: change
github-password: change
twitter-consumer-key: change
twitter-consumer-key-secret: change
twitter-access-token: change
twitter-access-token-secret: change 
